// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtYvUzQMZlkFwIKnJgYwEuPVi91J6UnBk',
    appId: '1:801742929500:web:0a81fb05f83c144425f099',
    messagingSenderId: '801742929500',
    projectId: 'chat-b8395',
    authDomain: 'chat-b8395.firebaseapp.com',
    storageBucket: 'chat-b8395.firebasestorage.app',
    measurementId: 'G-X0SQDZ0M2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBseVJXfqBhParM6_xisWFbwjeEGWXbZ1I',
    appId: '1:801742929500:android:ab6f0c8e42d6fa8525f099',
    messagingSenderId: '801742929500',
    projectId: 'chat-b8395',
    storageBucket: 'chat-b8395.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvZ4aEhxT4Iza_MMktCG1mKH1SvCgB6-o',
    appId: '1:801742929500:ios:2db722baba17a1dd25f099',
    messagingSenderId: '801742929500',
    projectId: 'chat-b8395',
    storageBucket: 'chat-b8395.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvZ4aEhxT4Iza_MMktCG1mKH1SvCgB6-o',
    appId: '1:801742929500:ios:2db722baba17a1dd25f099',
    messagingSenderId: '801742929500',
    projectId: 'chat-b8395',
    storageBucket: 'chat-b8395.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtYvUzQMZlkFwIKnJgYwEuPVi91J6UnBk',
    appId: '1:801742929500:web:1413a48311ad1aea25f099',
    messagingSenderId: '801742929500',
    projectId: 'chat-b8395',
    authDomain: 'chat-b8395.firebaseapp.com',
    storageBucket: 'chat-b8395.firebasestorage.app',
    measurementId: 'G-YR931MVX92',
  );
}
